import { CopyButton } from "./CopyButton";
import { IconChevron } from "./icons";

export function SqlResultPanel({ sql }: { sql: string }) {
  return (
    <div className="result-view__technical">
      <div className="result-view__panel-toolbar">
        <span className="help">SQL generated by Databricks Genie</span>
        <CopyButton text={sql} label="Copy SQL" />
      </div>
      <pre className="code result-view__code">
        <code>{sql}</code>
      </pre>
    </div>
  );
}

export function SqlDisclosure({ sql }: { sql: string }) {
  return (
    <details className="disclosure">
      <summary>
        <span className="row" style={{ gap: 8 }}>
          <IconChevron size={16} />
          Generated SQL
        </span>
        <span onClick={(e) => e.preventDefault()}>
          <CopyButton text={sql} label="Copy SQL" />
        </span>
      </summary>
      <pre className="code">
        <code>{sql}</code>
      </pre>
    </details>
  );
}
